name: Singularity build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # enable manual execution

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      SINGULARITY_VERSION: 3.7.2

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - uses: eWaterCycle/setup-singularity@v6
      with:
        singularity-version: ${{ env.SINGULARITY_VERSION }}

    - name: Singularity info
      run: |
        singularity --version

    - name: Build image
      run: |
        sudo singularity build image.sif Singularity.0.0.1
